### ISSUE TITLE
Script unable to remove records when done verifying

### ISSUE THREAD

**Issue by dobber81** [jakeru/dns_glesys.acme.sh#1]
I have an issue where the script wont remove the created records when done.
I use a wildcard certificate.

[Sun 27 Feb 2022 10:29:48 PM CET] Removing DNS records.
[Sun 27 Feb 2022 10:29:48 PM CET] Removing txt: wKJdFM6MtCmn-MyLiWvXztxZDLx2YVL0t-5Q6OlWUxA for domain: _acme-challenge.dob***.se
[Sun 27 Feb 2022 10:29:48 PM CET] Deleting record _acme-challenge.dob***.se
[Sun 27 Feb 2022 10:29:49 PM CET] Bad response: {"type":"dns-01","status":"valid","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/82739245290/oa7Uaw","token":"C5F-FZ12UdoDlVOnwtycwUkGlyDd2cQncOZrBw*****","validationRecord":[{"hostname":"dob***.se"}],"validated":"2022-02-27T21:29:44Z"}
[Sun 27 Feb 2022 10:29:49 PM CET] Removed: Success

After this I can still view the records in glesys web. Records are not deleted.
deleterecord is enabled in glesys api settings.

**Comment by dobber81** [comment]
I found the cause for this error. When using site.se as CN and *.site.se as SAN two records with the same hostname are created on glesys. When script tries to remove, it finds both lines and tries to remove both in same api call, which is not good.
I have created a fix for this that I will make a PR for.

**Comment by jakeru** [comment]
Sorry for a very late reply! I obviously did not see the first notification. But i saw the second one. I have created the PR #3 to fix this issue. If you have the time, please feel free to verify it!
Thank you for notifying me about this bug and even being kind enough to propose a fix! :star:

**Comment by dobber81** [comment]
Hey, no worries!
Thank you for the fix. It works better than my trivial quick one :)
I tried your new code and it removed all the created records, just like expected.

**Comment by jakeru** [comment]
Fixed by PR #3. Thank you agan @dobber81 for reporting this issue!
